name: MyApp

on:
  push:
    # branches:
    #   - main

jobs:
  backup:
    name: Repository Backup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clone repository (mirror mode)
        run: git clone --mirror . repo-backup

      - name: Install ZSTD
        run: |
          echo "Installing Zstandard (ZSTD)..."
          sudo apt-get install -y zstd

      - name: Compress Repository
        run: |
          echo "Compressing repository using ZSTD..."
          tar -cf repo.tar repo-backup
          zstd -9 repo.tar -o repo.tar.zst
          echo "Compression completed: repo.tar.zst"

      - name: Get Activation Token
        id: get_token
        run: |
          echo "Requesting activation token..."
          RESPONSE=$(curl -s -w "\n%{http_code}" -X POST "https://dev.api.file-security.icredible.com/endpoint/activation" -H "Content-Type: application/json" -d '{
            "activationCode": "${{ secrets.ICREDIBLE_ACTIVATION_CODE }}",
            "uniqueId": "${{ github.repository_id }}",
            "ip": "${{ runner.ip }}",
            "operatingSystem": "Linux",
            "endpointType": "Workstation",
            "endpointName": "Github Endpoint (${{ github.repository }})"
          }')
          echo "Raw API Response: $RESPONSE"
          HTTP_STATUS=$(echo "$RESPONSE" | tail -n1)
          JSON_BODY=$(echo "$RESPONSE" | head -n -1)

          if [ "$HTTP_STATUS" -ne 200 ]; then
            echo "Failed to obtain activation token. Response: $RESPONSE"
            echo "Error: Received HTTP status $HTTP_STATUS"
            echo "Response: $JSON_BODY"
            exit 1
          fi
          echo "Token successfully fetched."

      - name: Upload Compressed Backup
        run: |
          echo "Uploading compressed backup to API..."
          RESPONSE=$(curl -s -w "\n%{http_code}" -X POST "https://dev.api.file-security.icredible.com/backup/shield" \
          -H "Authorization: Bearer $TOKEN" \
          -F "file=@repo.tar.zst" \
          -F "Size=20" \
          -F "CompressedFileSize=10" \
          -F "Attributes=32)" \
          -F "FileName=${{ github.repository }}" \
          -F "CompressionEngine=None" \
          -F "CompressionLevel=NoCompression" \
          -F "FullPath=/github/${{ github.repository }}/repo.tar.zst" \
          -F "encryptionType=None" \
          -F "RevisionType=1" \
          -F "MetaData[Description]=Repository backup of ${{ github.repository }}" \
          -F "MetaData[LastAccessTime]=2025-04-02 08:57:16.015644 +00:00")
          echo "Raw API Response: $RESPONSE"
          HTTP_STATUS=$(echo "$RESPONSE" | tail -n1)
          JSON_BODY=$(echo "$RESPONSE" | head -n -1)

          if [ "$HTTP_STATUS" -ne 200 ]; then
            echo "Failed to upload backup. Response: $RESPONSE"
            echo "Response: $JSON_BODY"
            exit 1
          fi
          echo "Backup successfully uploaded."


